// <auto-generated />
using System;
using API.AirBnbInsights.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.AirBnbInsights.Migrations
{
    [DbContext(typeof(InsightsDbContext))]
    [Migration("20230621004231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.AirBnbInsights.Models.Listing", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<int?>("Accommodates")
                        .HasColumnType("int")
                        .HasColumnName("accommodates");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("amenities");

                    b.Property<int?>("Availability30")
                        .HasColumnType("int")
                        .HasColumnName("availability_30");

                    b.Property<int?>("Availability365")
                        .HasColumnType("int")
                        .HasColumnName("availability_365");

                    b.Property<int?>("Availability60")
                        .HasColumnType("int")
                        .HasColumnName("availability_60");

                    b.Property<int?>("Availability90")
                        .HasColumnType("int")
                        .HasColumnName("availability_90");

                    b.Property<decimal?>("Bathrooms")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("bathrooms");

                    b.Property<string>("BathroomsText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("bathrooms_text");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int")
                        .HasColumnName("bedrooms");

                    b.Property<int?>("Beds")
                        .HasColumnType("int")
                        .HasColumnName("beds");

                    b.Property<int>("CalculatedHostListingsCount")
                        .HasColumnType("int")
                        .HasColumnName("calculated_host_listings_count");

                    b.Property<int>("CalculatedHostListingsCountEntireHomes")
                        .HasColumnType("int")
                        .HasColumnName("calculated_host_listings_count_entire_homes");

                    b.Property<int>("CalculatedHostListingsCountPrivateRooms")
                        .HasColumnType("int")
                        .HasColumnName("calculated_host_listings_count_private_rooms");

                    b.Property<int>("CalculatedHostListingsCountSharedRooms")
                        .HasColumnType("int")
                        .HasColumnName("calculated_host_listings_count_shared_rooms");

                    b.Property<DateTime?>("CalendarLastScraped")
                        .HasColumnType("date")
                        .HasColumnName("calendar_last_scraped");

                    b.Property<DateTime?>("CalendarUpdated")
                        .HasColumnType("date")
                        .HasColumnName("calendar_updated");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FirstReview")
                        .HasColumnType("date")
                        .HasColumnName("first_review");

                    b.Property<string>("HasAvailability")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("has_availability")
                        .IsFixedLength();

                    b.Property<string>("HostAbout")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_about");

                    b.Property<string>("HostAcceptanceRate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_acceptance_rate");

                    b.Property<string>("HostHasProfilePic")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("host_has_profile_pic")
                        .IsFixedLength();

                    b.Property<int>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("host_id");

                    b.Property<string>("HostIdentityVerified")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("host_identity_verified")
                        .IsFixedLength();

                    b.Property<string>("HostIsSuperhost")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("host_is_superhost")
                        .IsFixedLength();

                    b.Property<string>("HostListingsCount")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_listings_count");

                    b.Property<string>("HostLocation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_location");

                    b.Property<string>("HostName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_name");

                    b.Property<string>("HostNeighbourhood")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_neighbourhood");

                    b.Property<string>("HostPictureUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_picture_url");

                    b.Property<string>("HostResponseRate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_response_rate");

                    b.Property<string>("HostResponseTime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_response_time");

                    b.Property<DateTime?>("HostSince")
                        .HasColumnType("date")
                        .HasColumnName("host_since");

                    b.Property<string>("HostThumbnailUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_thumbnail_url");

                    b.Property<string>("HostTotalListingsCount")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_total_listings_count");

                    b.Property<string>("HostUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_url");

                    b.Property<string>("HostVerifications")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_verifications");

                    b.Property<string>("InstantBookable")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("instant_bookable")
                        .IsFixedLength();

                    b.Property<DateTime?>("LastReview")
                        .HasColumnType("date")
                        .HasColumnName("last_review");

                    b.Property<DateTime>("LastScraped")
                        .HasColumnType("datetime")
                        .HasColumnName("last_scraped");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("latitude");

                    b.Property<string>("License")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("license");

                    b.Property<string>("ListingUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("listing_url");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("longitude");

                    b.Property<int?>("MaximumMaximumNights")
                        .HasColumnType("int")
                        .HasColumnName("maximum_maximum_nights");

                    b.Property<int?>("MaximumMinimumNights")
                        .HasColumnType("int")
                        .HasColumnName("maximum_minimum_nights");

                    b.Property<int?>("MaximumNights")
                        .HasColumnType("int")
                        .HasColumnName("maximum_nights");

                    b.Property<decimal?>("MaximumNightsAvgNtm")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("maximum_nights_avg_ntm");

                    b.Property<int?>("MinimumMaximumNights")
                        .HasColumnType("int")
                        .HasColumnName("minimum_maximum_nights");

                    b.Property<int?>("MinimumMinimumNights")
                        .HasColumnType("int")
                        .HasColumnName("minimum_minimum_nights");

                    b.Property<int?>("MinimumNights")
                        .HasColumnType("int")
                        .HasColumnName("minimum_nights");

                    b.Property<decimal?>("MinimumNightsAvgNtm")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("minimum_nights_avg_ntm");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("NeighborhoodOverview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("neighborhood_overview");

                    b.Property<string>("Neighbourhood")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("neighbourhood");

                    b.Property<string>("NeighbourhoodCleansed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("neighbourhood_cleansed");

                    b.Property<string>("NeighbourhoodGroupCleansed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("neighbourhood_group_cleansed");

                    b.Property<int?>("NumberOfReviews")
                        .HasColumnType("int")
                        .HasColumnName("number_of_reviews");

                    b.Property<int?>("NumberOfReviewsL30d")
                        .HasColumnType("int")
                        .HasColumnName("number_of_reviews_l30d");

                    b.Property<int?>("NumberOfReviewsLtm")
                        .HasColumnType("int")
                        .HasColumnName("number_of_reviews_ltm");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("picture_url");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("price");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("property_type");

                    b.Property<double?>("ReviewScoresAccuracy")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_accuracy");

                    b.Property<double?>("ReviewScoresCheckin")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_checkin");

                    b.Property<double?>("ReviewScoresCleanliness")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_cleanliness");

                    b.Property<double?>("ReviewScoresCommunication")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_communication");

                    b.Property<double?>("ReviewScoresLocation")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_location");

                    b.Property<double?>("ReviewScoresRating")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_rating");

                    b.Property<double?>("ReviewScoresValue")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_value");

                    b.Property<decimal?>("ReviewsPerMonth")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("reviews_per_month");

                    b.Property<string>("RoomType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("room_type");

                    b.Property<DateTime>("ScrapeId")
                        .HasColumnType("datetime2")
                        .HasColumnName("scrape_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("Listing", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
